/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { DeliverableVersion, ImpactSnapshot } from '../src/deliverable/types.ts'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$64656c6976657261626c6573 {
    invalidateDownstream: (rootVersionIds: string[]) => Promise<RemoteResult<ImpactSnapshot>>
    listCurrentInputs: (phaseRunId: string) => Promise<RemoteResult<DeliverableVersion[]>>
    listVersions: () => Promise<RemoteResult<DeliverableVersion[]>>
    saveVersion: (deliverableId: string, expectedBaseVersion: string | null, sourceSubmissionId: string | null, idempotencyKey?: string | null) => Promise<RemoteResult<DeliverableVersion>>
  }
  interface TypertRemoteMap {
    'deliverables/invalidateDownstream': (rootVersionIds: string[]) => Promise<RemoteResult<ImpactSnapshot>>
    'deliverables/listCurrentInputs': (phaseRunId: string) => Promise<RemoteResult<DeliverableVersion[]>>
    'deliverables/listVersions': () => Promise<RemoteResult<DeliverableVersion[]>>
    'deliverables/saveVersion': (deliverableId: string, expectedBaseVersion: string | null, sourceSubmissionId: string | null, idempotencyKey?: string | null) => Promise<RemoteResult<DeliverableVersion>>
  }
  interface TypertRemoteNamespaceMap {
    'deliverables': TypertRemoteNamespace$64656c6976657261626c6573
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
