/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_deliverable_local_deliverables_invalidateDownstream_parameter_0$schema = z.array(z.string())
const _deepseek_ai_dsh_deliverable_local_deliverables_invalidateDownstream_result$schema = z.object({
  'snapshotId': z.intersection(z.string(), z.unknown()).readonly(),
  'roots': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'staledVersions': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
})).readonly(),
  'affectedPhaseRuns': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'staledGateChecks': z.array(z.object({
  'submissionId': z.intersection(z.string(), z.unknown()).readonly(),
  'checkIds': z.array(z.string()).readonly(),
})).readonly(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deliverable_local_deliverables_listCurrentInputs_parameter_0$schema = z.string()
const _deepseek_ai_dsh_deliverable_local_deliverables_listCurrentInputs_result$schema = z.array(z.object({
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionNumber': z.number().readonly(),
  'baseVersionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sourceSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'dependsOn': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly().optional(),
  'state': z.union([z.literal("stale"), z.literal("cancelled"), z.literal("current"), z.literal("invalid"), z.literal("superseded")]).readonly(),
  'entityRevision': z.number().readonly(),
  'createdAt': z.number().readonly(),
}))
const _deepseek_ai_dsh_deliverable_local_deliverables_listVersions_result$schema = z.array(z.object({
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionNumber': z.number().readonly(),
  'baseVersionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sourceSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'dependsOn': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly().optional(),
  'state': z.union([z.literal("stale"), z.literal("cancelled"), z.literal("current"), z.literal("invalid"), z.literal("superseded")]).readonly(),
  'entityRevision': z.number().readonly(),
  'createdAt': z.number().readonly(),
}))
const _deepseek_ai_dsh_deliverable_local_deliverables_saveVersion_parameter_0$schema = z.string()
const _deepseek_ai_dsh_deliverable_local_deliverables_saveVersion_parameter_1$schema = z.union([z.literal(null), z.string()])
const _deepseek_ai_dsh_deliverable_local_deliverables_saveVersion_parameter_2$schema = z.union([z.literal(null), z.string()])
const _deepseek_ai_dsh_deliverable_local_deliverables_saveVersion_parameter_3$schema = z.union([z.undefined(), z.literal(null), z.string()])
const _deepseek_ai_dsh_deliverable_local_deliverables_saveVersion_result$schema = z.object({
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionNumber': z.number().readonly(),
  'baseVersionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sourceSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'dependsOn': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly().optional(),
  'state': z.union([z.literal("stale"), z.literal("cancelled"), z.literal("current"), z.literal("invalid"), z.literal("superseded")]).readonly(),
  'entityRevision': z.number().readonly(),
  'createdAt': z.number().readonly(),
})

export const TYPERT_REMOTE = {
  package: '@deepseek-ai/dsh-deliverable-local',
  descriptors: [
    {
      id: '@deepseek-ai/dsh-deliverable-local#deliverables/invalidateDownstream',
      service: 'deliverables',
      namespace: 'deliverables',
      method: 'invalidateDownstream',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rootVersionIds',
          wire: 'rootVersionIds',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deliverable-local#deliverables/invalidateDownstream:rootVersionIds',
            schema: _deepseek_ai_dsh_deliverable_local_deliverables_invalidateDownstream_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deliverable-local/types#ImpactSnapshot',
        schema: _deepseek_ai_dsh_deliverable_local_deliverables_invalidateDownstream_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/deliverable-local/src/index.ts","line":192,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deliverable-local#deliverables/listCurrentInputs',
      service: 'deliverables',
      namespace: 'deliverables',
      method: 'listCurrentInputs',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deliverable-local#deliverables/listCurrentInputs:phaseRunId',
            schema: _deepseek_ai_dsh_deliverable_local_deliverables_listCurrentInputs_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deliverable-local#deliverables/listCurrentInputs:result',
        schema: _deepseek_ai_dsh_deliverable_local_deliverables_listCurrentInputs_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/deliverable-local/src/index.ts","line":156,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deliverable-local#deliverables/listVersions',
      service: 'deliverables',
      namespace: 'deliverables',
      method: 'listVersions',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deliverable-local#deliverables/listVersions:result',
        schema: _deepseek_ai_dsh_deliverable_local_deliverables_listVersions_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/deliverable-local/src/index.ts","line":175,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deliverable-local#deliverables/saveVersion',
      service: 'deliverables',
      namespace: 'deliverables',
      method: 'saveVersion',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'deliverableId',
          wire: 'deliverableId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deliverable-local#deliverables/saveVersion:deliverableId',
            schema: _deepseek_ai_dsh_deliverable_local_deliverables_saveVersion_parameter_0$schema,
          },
        },
        {
          name: 'expectedBaseVersion',
          wire: 'expectedBaseVersion',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deliverable-local#deliverables/saveVersion:expectedBaseVersion',
            schema: _deepseek_ai_dsh_deliverable_local_deliverables_saveVersion_parameter_1$schema,
          },
        },
        {
          name: 'sourceSubmissionId',
          wire: 'sourceSubmissionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deliverable-local#deliverables/saveVersion:sourceSubmissionId',
            schema: _deepseek_ai_dsh_deliverable_local_deliverables_saveVersion_parameter_2$schema,
          },
        },
        {
          name: 'idempotencyKey',
          wire: 'idempotencyKey',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deliverable-local#deliverables/saveVersion:idempotencyKey',
            schema: _deepseek_ai_dsh_deliverable_local_deliverables_saveVersion_parameter_3$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deliverable-local/types#DeliverableVersion',
        schema: _deepseek_ai_dsh_deliverable_local_deliverables_saveVersion_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/deliverable-local/src/index.ts","line":125,"column":3},
    },
  ],
}

export default TYPERT_REMOTE
