/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_digest_digest_digest_parameter_0$schema = z.string()
const _deepseek_ai_dsh_digest_digest_digest_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'state': z.string().readonly(),
  'revision': z.number().readonly(),
  'runs': z.array(z.object({
  'runId': z.string().readonly(),
  'parentRunId': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
  'supersededAt': z.number().readonly().optional(),
})).readonly(),
  'timeline': z.array(z.object({
  'seq': z.number().readonly(),
  'kind': z.string().readonly(),
  'occurredAt': z.number().readonly(),
  'actor': z.string().readonly(),
  'summary': z.string().readonly(),
})).readonly(),
  'phaseSummaries': z.array(z.object({
  'phaseId': z.string().readonly(),
  'state': z.string().readonly(),
  'attemptCount': z.number().readonly(),
  'passedAt': z.number().readonly().optional(),
  'failedAt': z.number().readonly().optional(),
})).readonly(),
  'decisionHistory': z.array(z.object({
  'decisionKind': z.string().readonly(),
  'outcome': z.string().readonly().optional(),
  'resolvedAt': z.number().readonly().optional(),
})).readonly(),
  'deliverableStates': z.array(z.object({
  'deliverableId': z.string().readonly(),
  'currentVersionId': z.string().readonly().optional(),
  'state': z.string().readonly(),
  'versionCount': z.number().readonly(),
})).readonly(),
})

export const TYPERT_REMOTE = {
  package: '@deepseek-ai/dsh-digest',
  descriptors: [
    {
      id: '@deepseek-ai/dsh-digest#digest/digest',
      service: 'digest',
      namespace: 'digest',
      method: 'digest',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-digest#digest/digest:taskId',
            schema: _deepseek_ai_dsh_digest_digest_digest_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-digest/types#TaskDigest',
        schema: _deepseek_ai_dsh_digest_digest_digest_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/digest/src/index.ts","line":55,"column":9},
    },
  ],
}

export default TYPERT_REMOTE
