/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { TaskDigest } from '../src/digest/types.ts'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$646967657374 {
    digest: (taskId: string) => Promise<RemoteResult<TaskDigest>>
  }
  interface TypertRemoteMap {
    'digest/digest': (taskId: string) => Promise<RemoteResult<TaskDigest>>
  }
  interface TypertRemoteNamespaceMap {
    'digest': TypertRemoteNamespace$646967657374
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
