/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { TaskMetrics, WorkbenchMetrics } from '../src/metrics/types.ts'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d657472696373 {
    metrics: () => Promise<RemoteResult<WorkbenchMetrics>>
    taskMetrics: (taskId: string) => Promise<RemoteResult<TaskMetrics>>
  }
  interface TypertRemoteMap {
    'metrics/metrics': () => Promise<RemoteResult<WorkbenchMetrics>>
    'metrics/taskMetrics': (taskId: string) => Promise<RemoteResult<TaskMetrics>>
  }
  interface TypertRemoteNamespaceMap {
    'metrics': TypertRemoteNamespace$6d657472696373
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
