/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_metrics_metrics_metrics_result$schema = z.object({
  'live': z.number().readonly(),
  'gate': z.number().readonly(),
  'ask': z.number().readonly(),
  'asset': z.number().readonly(),
  'throughput': z.array(z.object({
  'day': z.string().readonly(),
  'completedPhases': z.number().readonly(),
})).readonly(),
  'gatePassRate': z.object({
  'a': z.number().readonly(),
  'b': z.number().readonly(),
  'c': z.number().readonly(),
}).readonly(),
})
const _deepseek_ai_dsh_metrics_metrics_taskMetrics_parameter_0$schema = z.string()
const _deepseek_ai_dsh_metrics_metrics_taskMetrics_result$schema = z.object({
  'taskId': z.string().readonly(),
  'phaseDurations': z.array(z.object({
  'phaseId': z.string().readonly(),
  'startedAt': z.number().readonly().optional(),
  'passedAt': z.number().readonly().optional(),
  'durationMs': z.number().readonly().optional(),
})).readonly(),
  'rerunCount': z.number().readonly(),
  'decisionCount': z.number().readonly(),
  'budgetUsed': z.object({
  'tokens': z.number().readonly(),
  'durationMs': z.number().readonly(),
  'reruns': z.number().readonly(),
}).readonly().optional(),
})

export const TYPERT_REMOTE = {
  package: '@deepseek-ai/dsh-metrics',
  descriptors: [
    {
      id: '@deepseek-ai/dsh-metrics#metrics/metrics',
      service: 'metrics',
      namespace: 'metrics',
      method: 'metrics',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-metrics/types#WorkbenchMetrics',
        schema: _deepseek_ai_dsh_metrics_metrics_metrics_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/metrics/src/index.ts","line":55,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-metrics#metrics/taskMetrics',
      service: 'metrics',
      namespace: 'metrics',
      method: 'taskMetrics',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-metrics#metrics/taskMetrics:taskId',
            schema: _deepseek_ai_dsh_metrics_metrics_taskMetrics_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-metrics/types#TaskMetrics',
        schema: _deepseek_ai_dsh_metrics_metrics_taskMetrics_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/metrics/src/index.ts","line":71,"column":9},
    },
  ],
}

export default TYPERT_REMOTE
