/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { RecipeIdentity, RecipePayload, RecipeRevision } from '../src/recipe/types.ts'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$72656369706573 {
    getPinned: (identity: RecipeIdentity) => Promise<RemoteResult<RecipeRevision>>
    latest: (recipeId: string) => Promise<RemoteResult<RecipeRevision | undefined>>
    list: () => Promise<RemoteResult<RecipeIdentity[]>>
    listDetails: () => Promise<RemoteResult<RecipeRevision[]>>
    register: (recipeId: string, revision: number, payload: RecipePayload) => Promise<RemoteResult<RecipeRevision>>
  }
  interface TypertRemoteMap {
    'recipes/getPinned': (identity: RecipeIdentity) => Promise<RemoteResult<RecipeRevision>>
    'recipes/latest': (recipeId: string) => Promise<RemoteResult<RecipeRevision | undefined>>
    'recipes/list': () => Promise<RemoteResult<RecipeIdentity[]>>
    'recipes/listDetails': () => Promise<RemoteResult<RecipeRevision[]>>
    'recipes/register': (recipeId: string, revision: number, payload: RecipePayload) => Promise<RemoteResult<RecipeRevision>>
  }
  interface TypertRemoteNamespaceMap {
    'recipes': TypertRemoteNamespace$72656369706573
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
