/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_recipe_recipes_getPinned_parameter_0$schema = z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
})
const _deepseek_ai_dsh_recipe_recipes_getPinned_result$schema = z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'payload': z.object({
  'phases': z.array(z.object({
  'phaseId': z.string().readonly(),
  'kind': z.string().readonly(),
  'goal': z.string().readonly(),
  'inputs': z.array(z.string()).readonly(),
  'outputs': z.array(z.string()).readonly(),
  'submissionCriteria': z.array(z.string()).readonly(),
})).readonly(),
  'gateChecks': z.array(z.object({
  'checkId': z.string().readonly(),
  'phaseId': z.string().readonly(),
  'kind': z.union([z.literal("A"), z.literal("B"), z.literal("C")]).readonly(),
  'machineScope': z.array(z.string()).readonly(),
  'humanAction': z.array(z.string()).readonly(),
  'circuitBreaker': z.string().readonly().optional(),
})).readonly(),
  'defaults': z.object({
  'batchConfirm': z.union([z.literal("per-phase-single"), z.literal("per-check")]).readonly(),
  'clarify': z.object({
  'maxRounds': z.number().readonly(),
  'splitMustDefault': z.boolean().readonly(),
}).readonly(),
  'draftPolicy': z.literal("block-finalize-not-draft").readonly(),
}).readonly(),
  'p4Mode': z.object({
  'mode': z.union([z.literal("auto"), z.literal("draft"), z.literal("skeleton"), z.literal("verify-normalize")]).readonly(),
}).readonly(),
  'breakers': z.array(z.object({
  'key': z.string().readonly(),
  'maxConsecutiveRepairs': z.number().readonly(),
})).readonly().optional(),
}).readonly(),
  'registeredAt': z.number().readonly(),
})
const _deepseek_ai_dsh_recipe_recipes_latest_parameter_0$schema = z.string()
const _deepseek_ai_dsh_recipe_recipes_latest_result$schema = z.union([z.undefined(), z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'payload': z.object({
  'phases': z.array(z.object({
  'phaseId': z.string().readonly(),
  'kind': z.string().readonly(),
  'goal': z.string().readonly(),
  'inputs': z.array(z.string()).readonly(),
  'outputs': z.array(z.string()).readonly(),
  'submissionCriteria': z.array(z.string()).readonly(),
})).readonly(),
  'gateChecks': z.array(z.object({
  'checkId': z.string().readonly(),
  'phaseId': z.string().readonly(),
  'kind': z.union([z.literal("A"), z.literal("B"), z.literal("C")]).readonly(),
  'machineScope': z.array(z.string()).readonly(),
  'humanAction': z.array(z.string()).readonly(),
  'circuitBreaker': z.string().readonly().optional(),
})).readonly(),
  'defaults': z.object({
  'batchConfirm': z.union([z.literal("per-phase-single"), z.literal("per-check")]).readonly(),
  'clarify': z.object({
  'maxRounds': z.number().readonly(),
  'splitMustDefault': z.boolean().readonly(),
}).readonly(),
  'draftPolicy': z.literal("block-finalize-not-draft").readonly(),
}).readonly(),
  'p4Mode': z.object({
  'mode': z.union([z.literal("auto"), z.literal("draft"), z.literal("skeleton"), z.literal("verify-normalize")]).readonly(),
}).readonly(),
  'breakers': z.array(z.object({
  'key': z.string().readonly(),
  'maxConsecutiveRepairs': z.number().readonly(),
})).readonly().optional(),
}).readonly(),
  'registeredAt': z.number().readonly(),
})])
const _deepseek_ai_dsh_recipe_recipes_list_result$schema = z.array(z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
}))
const _deepseek_ai_dsh_recipe_recipes_listDetails_result$schema = z.array(z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'payload': z.object({
  'phases': z.array(z.object({
  'phaseId': z.string().readonly(),
  'kind': z.string().readonly(),
  'goal': z.string().readonly(),
  'inputs': z.array(z.string()).readonly(),
  'outputs': z.array(z.string()).readonly(),
  'submissionCriteria': z.array(z.string()).readonly(),
})).readonly(),
  'gateChecks': z.array(z.object({
  'checkId': z.string().readonly(),
  'phaseId': z.string().readonly(),
  'kind': z.union([z.literal("A"), z.literal("B"), z.literal("C")]).readonly(),
  'machineScope': z.array(z.string()).readonly(),
  'humanAction': z.array(z.string()).readonly(),
  'circuitBreaker': z.string().readonly().optional(),
})).readonly(),
  'defaults': z.object({
  'batchConfirm': z.union([z.literal("per-phase-single"), z.literal("per-check")]).readonly(),
  'clarify': z.object({
  'maxRounds': z.number().readonly(),
  'splitMustDefault': z.boolean().readonly(),
}).readonly(),
  'draftPolicy': z.literal("block-finalize-not-draft").readonly(),
}).readonly(),
  'p4Mode': z.object({
  'mode': z.union([z.literal("auto"), z.literal("draft"), z.literal("skeleton"), z.literal("verify-normalize")]).readonly(),
}).readonly(),
  'breakers': z.array(z.object({
  'key': z.string().readonly(),
  'maxConsecutiveRepairs': z.number().readonly(),
})).readonly().optional(),
}).readonly(),
  'registeredAt': z.number().readonly(),
}))
const _deepseek_ai_dsh_recipe_recipes_register_parameter_0$schema = z.string()
const _deepseek_ai_dsh_recipe_recipes_register_parameter_1$schema = z.number()
const _deepseek_ai_dsh_recipe_recipes_register_parameter_2$schema = z.object({
  'phases': z.array(z.object({
  'phaseId': z.string().readonly(),
  'kind': z.string().readonly(),
  'goal': z.string().readonly(),
  'inputs': z.array(z.string()).readonly(),
  'outputs': z.array(z.string()).readonly(),
  'submissionCriteria': z.array(z.string()).readonly(),
})).readonly(),
  'gateChecks': z.array(z.object({
  'checkId': z.string().readonly(),
  'phaseId': z.string().readonly(),
  'kind': z.union([z.literal("A"), z.literal("B"), z.literal("C")]).readonly(),
  'machineScope': z.array(z.string()).readonly(),
  'humanAction': z.array(z.string()).readonly(),
  'circuitBreaker': z.string().readonly().optional(),
})).readonly(),
  'defaults': z.object({
  'batchConfirm': z.union([z.literal("per-phase-single"), z.literal("per-check")]).readonly(),
  'clarify': z.object({
  'maxRounds': z.number().readonly(),
  'splitMustDefault': z.boolean().readonly(),
}).readonly(),
  'draftPolicy': z.literal("block-finalize-not-draft").readonly(),
}).readonly(),
  'p4Mode': z.object({
  'mode': z.union([z.literal("auto"), z.literal("draft"), z.literal("skeleton"), z.literal("verify-normalize")]).readonly(),
}).readonly(),
  'breakers': z.array(z.object({
  'key': z.string().readonly(),
  'maxConsecutiveRepairs': z.number().readonly(),
})).readonly().optional(),
})
const _deepseek_ai_dsh_recipe_recipes_register_result$schema = z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'payload': z.object({
  'phases': z.array(z.object({
  'phaseId': z.string().readonly(),
  'kind': z.string().readonly(),
  'goal': z.string().readonly(),
  'inputs': z.array(z.string()).readonly(),
  'outputs': z.array(z.string()).readonly(),
  'submissionCriteria': z.array(z.string()).readonly(),
})).readonly(),
  'gateChecks': z.array(z.object({
  'checkId': z.string().readonly(),
  'phaseId': z.string().readonly(),
  'kind': z.union([z.literal("A"), z.literal("B"), z.literal("C")]).readonly(),
  'machineScope': z.array(z.string()).readonly(),
  'humanAction': z.array(z.string()).readonly(),
  'circuitBreaker': z.string().readonly().optional(),
})).readonly(),
  'defaults': z.object({
  'batchConfirm': z.union([z.literal("per-phase-single"), z.literal("per-check")]).readonly(),
  'clarify': z.object({
  'maxRounds': z.number().readonly(),
  'splitMustDefault': z.boolean().readonly(),
}).readonly(),
  'draftPolicy': z.literal("block-finalize-not-draft").readonly(),
}).readonly(),
  'p4Mode': z.object({
  'mode': z.union([z.literal("auto"), z.literal("draft"), z.literal("skeleton"), z.literal("verify-normalize")]).readonly(),
}).readonly(),
  'breakers': z.array(z.object({
  'key': z.string().readonly(),
  'maxConsecutiveRepairs': z.number().readonly(),
})).readonly().optional(),
}).readonly(),
  'registeredAt': z.number().readonly(),
})

export const TYPERT_REMOTE = {
  package: '@deepseek-ai/dsh-recipe',
  descriptors: [
    {
      id: '@deepseek-ai/dsh-recipe#recipes/getPinned',
      service: 'recipes',
      namespace: 'recipes',
      method: 'getPinned',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'identity',
          wire: 'identity',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-recipe/types#RecipeIdentity',
            schema: _deepseek_ai_dsh_recipe_recipes_getPinned_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-recipe/types#RecipeRevision',
        schema: _deepseek_ai_dsh_recipe_recipes_getPinned_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/recipe/src/index.ts","line":211,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-recipe#recipes/latest',
      service: 'recipes',
      namespace: 'recipes',
      method: 'latest',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'recipeId',
          wire: 'recipeId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-recipe#recipes/latest:recipeId',
            schema: _deepseek_ai_dsh_recipe_recipes_latest_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-recipe#recipes/latest:result',
        schema: _deepseek_ai_dsh_recipe_recipes_latest_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/recipe/src/index.ts","line":226,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-recipe#recipes/list',
      service: 'recipes',
      namespace: 'recipes',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-recipe#recipes/list:result',
        schema: _deepseek_ai_dsh_recipe_recipes_list_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/recipe/src/index.ts","line":241,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-recipe#recipes/listDetails',
      service: 'recipes',
      namespace: 'recipes',
      method: 'listDetails',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-recipe#recipes/listDetails:result',
        schema: _deepseek_ai_dsh_recipe_recipes_listDetails_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/recipe/src/index.ts","line":251,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-recipe#recipes/register',
      service: 'recipes',
      namespace: 'recipes',
      method: 'register',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'recipeId',
          wire: 'recipeId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-recipe#recipes/register:recipeId',
            schema: _deepseek_ai_dsh_recipe_recipes_register_parameter_0$schema,
          },
        },
        {
          name: 'revision',
          wire: 'revision',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-recipe#recipes/register:revision',
            schema: _deepseek_ai_dsh_recipe_recipes_register_parameter_1$schema,
          },
        },
        {
          name: 'payload',
          wire: 'payload',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-recipe/types#RecipePayload',
            schema: _deepseek_ai_dsh_recipe_recipes_register_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-recipe/types#RecipeRevision',
        schema: _deepseek_ai_dsh_recipe_recipes_register_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/recipe/src/index.ts","line":170,"column":3},
    },
  ],
}

export default TYPERT_REMOTE
