/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { RewindApplication, RewindPreview } from '../src/rewind/types.ts'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$726577696e64 {
    applyRewind: (itemId: string, taskRevision: number, actor: string, idempotencyKey: string) => Promise<RemoteResult<RewindApplication>>
    requestRewind: (taskId: string, rootVersionIds: string[], actor: string, idempotencyKey: string) => Promise<RemoteResult<RewindPreview & { itemId: string; }>>
  }
  interface TypertRemoteMap {
    'rewind/applyRewind': (itemId: string, taskRevision: number, actor: string, idempotencyKey: string) => Promise<RemoteResult<RewindApplication>>
    'rewind/requestRewind': (taskId: string, rootVersionIds: string[], actor: string, idempotencyKey: string) => Promise<RemoteResult<RewindPreview & { itemId: string; }>>
  }
  interface TypertRemoteNamespaceMap {
    'rewind': TypertRemoteNamespace$726577696e64
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
