/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_rewind_rewind_applyRewind_parameter_0$schema = z.string()
const _deepseek_ai_dsh_rewind_rewind_applyRewind_parameter_1$schema = z.number()
const _deepseek_ai_dsh_rewind_rewind_applyRewind_parameter_2$schema = z.string()
const _deepseek_ai_dsh_rewind_rewind_applyRewind_parameter_3$schema = z.string()
const _deepseek_ai_dsh_rewind_rewind_applyRewind_result$schema = z.object({
  'run': z.object({
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'revision': z.number().readonly(),
  'parentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'createdAt': z.number().readonly(),
}).readonly(),
  'supersededPhaseRunIds': z.array(z.string()).readonly(),
})
const _deepseek_ai_dsh_rewind_rewind_requestRewind_parameter_0$schema = z.string()
const _deepseek_ai_dsh_rewind_rewind_requestRewind_parameter_1$schema = z.array(z.string())
const _deepseek_ai_dsh_rewind_rewind_requestRewind_parameter_2$schema = z.string()
const _deepseek_ai_dsh_rewind_rewind_requestRewind_parameter_3$schema = z.string()
const _deepseek_ai_dsh_rewind_rewind_requestRewind_result$schema = z.intersection(z.object({
  'snapshotId': z.string().readonly(),
  'invalidatedVersionIds': z.array(z.string()).readonly(),
  'rerunPhaseIds': z.array(z.string()).readonly(),
  'reusableClarificationIds': z.array(z.string()).readonly(),
  'costHint': z.literal("uncalibrated").readonly(),
}), z.object({
  'itemId': z.string(),
}))

export const TYPERT_REMOTE = {
  package: '@deepseek-ai/dsh-rewind',
  descriptors: [
    {
      id: '@deepseek-ai/dsh-rewind#rewind/applyRewind',
      service: 'rewind',
      namespace: 'rewind',
      method: 'applyRewind',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'itemId',
          wire: 'itemId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-rewind#rewind/applyRewind:itemId',
            schema: _deepseek_ai_dsh_rewind_rewind_applyRewind_parameter_0$schema,
          },
        },
        {
          name: 'taskRevision',
          wire: 'taskRevision',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-rewind#rewind/applyRewind:taskRevision',
            schema: _deepseek_ai_dsh_rewind_rewind_applyRewind_parameter_1$schema,
          },
        },
        {
          name: 'actor',
          wire: 'actor',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-rewind#rewind/applyRewind:actor',
            schema: _deepseek_ai_dsh_rewind_rewind_applyRewind_parameter_2$schema,
          },
        },
        {
          name: 'idempotencyKey',
          wire: 'idempotencyKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-rewind#rewind/applyRewind:idempotencyKey',
            schema: _deepseek_ai_dsh_rewind_rewind_applyRewind_parameter_3$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-rewind/types#RewindApplication',
        schema: _deepseek_ai_dsh_rewind_rewind_applyRewind_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/rewind/src/index.ts","line":92,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-rewind#rewind/requestRewind',
      service: 'rewind',
      namespace: 'rewind',
      method: 'requestRewind',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-rewind#rewind/requestRewind:taskId',
            schema: _deepseek_ai_dsh_rewind_rewind_requestRewind_parameter_0$schema,
          },
        },
        {
          name: 'rootVersionIds',
          wire: 'rootVersionIds',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-rewind#rewind/requestRewind:rootVersionIds',
            schema: _deepseek_ai_dsh_rewind_rewind_requestRewind_parameter_1$schema,
          },
        },
        {
          name: 'actor',
          wire: 'actor',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-rewind#rewind/requestRewind:actor',
            schema: _deepseek_ai_dsh_rewind_rewind_requestRewind_parameter_2$schema,
          },
        },
        {
          name: 'idempotencyKey',
          wire: 'idempotencyKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-rewind#rewind/requestRewind:idempotencyKey',
            schema: _deepseek_ai_dsh_rewind_rewind_requestRewind_parameter_3$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-rewind#rewind/requestRewind:result',
        schema: _deepseek_ai_dsh_rewind_rewind_requestRewind_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/rewind/src/index.ts","line":64,"column":9},
    },
  ],
}

export default TYPERT_REMOTE
