/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_task_tasks_cancelPhaseRun_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_cancelPhaseRun_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_cancelPhaseRun_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_clearPhaseScheduling_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_clearPhaseScheduling_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_clearPhaseScheduling_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_completeTask_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_completeTask_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_completeTask_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_1$schema = z.string()
const _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_2$schema = z.boolean()
const _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_3$schema = z.string()
const _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_4$schema = z.string()
const _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_5$schema = z.string()
const _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_6$schema = z.string()
const _deepseek_ai_dsh_task_tasks_confirmCreateTask_result$schema = z.object({
  'task': z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
}).readonly(),
  'created': z.boolean().readonly(),
  'seedPoints': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_createPhaseRun_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_createPhaseRun_parameter_1$schema = z.string()
const _deepseek_ai_dsh_task_tasks_createPhaseRun_parameter_2$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_createPhaseRun_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_createTask_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_createTask_parameter_1$schema = z.string()
const _deepseek_ai_dsh_task_tasks_createTask_parameter_2$schema = z.string()
const _deepseek_ai_dsh_task_tasks_createTask_parameter_3$schema = z.string()
const _deepseek_ai_dsh_task_tasks_createTask_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_createTaskRun_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_createTaskRun_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_createTaskRun_parameter_2$schema = z.union([z.undefined(), z.string()])
const _deepseek_ai_dsh_task_tasks_createTaskRun_result$schema = z.object({
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'revision': z.number().readonly(),
  'parentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_failTask_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_failTask_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_failTask_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_freezePhaseScheduling_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_freezePhaseScheduling_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_freezePhaseScheduling_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_getPhaseRun_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_getPhaseRun_result$schema = z.union([z.undefined(), z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})])
const _deepseek_ai_dsh_task_tasks_getSubmission_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_getSubmission_result$schema = z.union([z.undefined(), z.object({
  'submissionId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'attempt': z.number().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'sourceSessionId': z.string().readonly(),
  'sourceSeqRange': z.object({
  'start': z.number().readonly(),
  'end': z.number().readonly(),
}).readonly(),
  'inputVersions': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
  'outputVersions': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
  'unresolvedIssues': z.array(z.string()).readonly(),
  'result': z.union([z.literal("failed"), z.literal("completed"), z.literal("needs-clarification")]).readonly(),
  'failureReason': z.string().readonly().optional(),
  'idempotencyKey': z.string().readonly(),
  'submittedAt': z.number().readonly(),
  'supersedesSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
})])
const _deepseek_ai_dsh_task_tasks_getTask_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_getTask_result$schema = z.union([z.undefined(), z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})])
const _deepseek_ai_dsh_task_tasks_listGateResults_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_listGateResults_result$schema = z.array(z.object({
  'submissionId': z.intersection(z.string(), z.unknown()).readonly(),
  'checkId': z.string().readonly(),
  'passed': z.boolean().readonly(),
  'kind': z.union([z.literal("A"), z.literal("B"), z.literal("C")]).readonly().optional(),
  'detail': z.string().readonly().optional(),
  'recordedAt': z.number().readonly(),
  'stale': z.boolean().readonly().optional(),
  'uncoveredScope': z.array(z.string()).readonly().optional(),
  'evidenceRefs': z.array(z.string()).readonly().optional(),
}))
const _deepseek_ai_dsh_task_tasks_listPhaseRuns_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_listPhaseRuns_result$schema = z.array(z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
}))
const _deepseek_ai_dsh_task_tasks_listTasks_result$schema = z.array(z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
}))
const _deepseek_ai_dsh_task_tasks_markGateChecksStale_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_markGateChecksStale_parameter_1$schema = z.array(z.string())
const _deepseek_ai_dsh_task_tasks_markGateChecksStale_parameter_2$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_markGateChecksStale_result$schema = z.array(z.object({
  'submissionId': z.intersection(z.string(), z.unknown()).readonly(),
  'checkId': z.string().readonly(),
  'passed': z.boolean().readonly(),
  'kind': z.union([z.literal("A"), z.literal("B"), z.literal("C")]).readonly().optional(),
  'detail': z.string().readonly().optional(),
  'recordedAt': z.number().readonly(),
  'stale': z.boolean().readonly().optional(),
  'uncoveredScope': z.array(z.string()).readonly().optional(),
  'evidenceRefs': z.array(z.string()).readonly().optional(),
}))
const _deepseek_ai_dsh_task_tasks_markPhaseAwaitingDecision_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_markPhaseAwaitingDecision_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_markPhaseAwaitingDecision_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_markPhaseAwaitingInput_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_markPhaseAwaitingInput_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_markPhaseAwaitingInput_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_markPhaseFailed_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_markPhaseFailed_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_markPhaseFailed_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_markPhasePassed_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_markPhasePassed_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_markPhasePassed_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_markPhaseStale_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_markPhaseStale_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_markPhaseStale_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_markPhaseSuperseded_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_markPhaseSuperseded_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_markPhaseSuperseded_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_markTaskAwaitingDecision_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_markTaskAwaitingDecision_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_markTaskAwaitingDecision_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_recordGateCheck_parameter_0$schema = z.object({
  'submissionId': z.intersection(z.string(), z.unknown()).readonly(),
  'checkId': z.string().readonly(),
  'passed': z.boolean().readonly(),
  'kind': z.union([z.literal("A"), z.literal("B"), z.literal("C")]).readonly().optional(),
  'detail': z.string().readonly().optional(),
  'recordedAt': z.number().readonly(),
  'stale': z.boolean().readonly().optional(),
  'uncoveredScope': z.array(z.string()).readonly().optional(),
  'evidenceRefs': z.array(z.string()).readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_recordGateCheck_result$schema = z.object({
  'submissionId': z.intersection(z.string(), z.unknown()).readonly(),
  'checkId': z.string().readonly(),
  'passed': z.boolean().readonly(),
  'kind': z.union([z.literal("A"), z.literal("B"), z.literal("C")]).readonly().optional(),
  'detail': z.string().readonly().optional(),
  'recordedAt': z.number().readonly(),
  'stale': z.boolean().readonly().optional(),
  'uncoveredScope': z.array(z.string()).readonly().optional(),
  'evidenceRefs': z.array(z.string()).readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_recordPhaseSession_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_recordPhaseSession_parameter_1$schema = z.string()
const _deepseek_ai_dsh_task_tasks_recordPhaseSession_parameter_2$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_recordPhaseSession_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_recordSubmission_parameter_0$schema = z.object({
  'submissionId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'attempt': z.number().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'sourceSessionId': z.string().readonly(),
  'sourceSeqRange': z.object({
  'start': z.number().readonly(),
  'end': z.number().readonly(),
}).readonly(),
  'inputVersions': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
  'outputVersions': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
  'unresolvedIssues': z.array(z.string()).readonly(),
  'result': z.union([z.literal("failed"), z.literal("completed"), z.literal("needs-clarification")]).readonly(),
  'failureReason': z.string().readonly().optional(),
  'idempotencyKey': z.string().readonly(),
  'submittedAt': z.number().readonly(),
  'supersedesSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_recordSubmission_parameter_1$schema = z.object({
  'submittedBy': z.string().readonly(),
  'sourceSeqPersisted': z.boolean().readonly(),
  'inputsCurrent': z.boolean().readonly(),
  'outputsValid': z.boolean().readonly(),
})
const _deepseek_ai_dsh_task_tasks_recordSubmission_result$schema = z.object({
  'submissionId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'attempt': z.number().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'sourceSessionId': z.string().readonly(),
  'sourceSeqRange': z.object({
  'start': z.number().readonly(),
  'end': z.number().readonly(),
}).readonly(),
  'inputVersions': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
  'outputVersions': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
  'unresolvedIssues': z.array(z.string()).readonly(),
  'result': z.union([z.literal("failed"), z.literal("completed"), z.literal("needs-clarification")]).readonly(),
  'failureReason': z.string().readonly().optional(),
  'idempotencyKey': z.string().readonly(),
  'submittedAt': z.number().readonly(),
  'supersedesSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_requestCancel_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_requestCancel_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_requestCancel_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_requestPatch_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_requestPatch_parameter_1$schema = z.string()
const _deepseek_ai_dsh_task_tasks_requestPatch_parameter_2$schema = z.string()
const _deepseek_ai_dsh_task_tasks_requestPatch_parameter_3$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_requestPatch_result$schema = z.object({
  'submissionId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'attempt': z.number().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'sourceSessionId': z.string().readonly(),
  'sourceSeqRange': z.object({
  'start': z.number().readonly(),
  'end': z.number().readonly(),
}).readonly(),
  'inputVersions': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
  'outputVersions': z.array(z.object({
  'deliverableId': z.intersection(z.string(), z.unknown()).readonly(),
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
  'unresolvedIssues': z.array(z.string()).readonly(),
  'result': z.union([z.literal("failed"), z.literal("completed"), z.literal("needs-clarification")]).readonly(),
  'failureReason': z.string().readonly().optional(),
  'idempotencyKey': z.string().readonly(),
  'submittedAt': z.number().readonly(),
  'supersedesSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_requestPause_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_requestPause_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_requestPause_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_resume_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_resume_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_resume_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_resumePhaseFromAwaiting_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_resumePhaseFromAwaiting_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_resumePhaseFromAwaiting_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_resumeTaskFromDecision_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_resumeTaskFromDecision_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_resumeTaskFromDecision_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_settleCancel_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_settleCancel_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_settleCancel_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_settlePause_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_settlePause_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_settlePause_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})
const _deepseek_ai_dsh_task_tasks_startGate_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_startGate_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_startGate_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_startPhaseRun_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_startPhaseRun_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_startPhaseRun_result$schema = z.object({
  'phaseRunId': z.intersection(z.string(), z.unknown()).readonly(),
  'runId': z.intersection(z.string(), z.unknown()).readonly(),
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'phaseId': z.string().readonly(),
  'state': z.union([z.literal("stale"), z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("superseded"), z.literal("created"), z.literal("scheduled"), z.literal("submitting"), z.literal("submitted"), z.literal("gate-running"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("patching"), z.literal("passed")]).readonly(),
  'revision': z.number().readonly(),
  'activeSubmissionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'sessionId': z.string().readonly().optional(),
  'schedulingFrozen': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_task_tasks_startTask_parameter_0$schema = z.string()
const _deepseek_ai_dsh_task_tasks_startTask_parameter_1$schema = z.object({
  'actor': z.string().readonly(),
  'reason': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
  'idempotencyKey': z.string().readonly(),
})
const _deepseek_ai_dsh_task_tasks_startTask_result$schema = z.object({
  'taskId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.string().readonly(),
  'pinnedRecipe': z.object({
  'recipeId': z.intersection(z.string(), z.unknown()).readonly(),
  'revision': z.number().readonly(),
  'schemaVersion': z.number().readonly(),
  'contentHash': z.string().readonly(),
}).readonly(),
  'state': z.union([z.literal("running"), z.literal("cancelled"), z.literal("failed"), z.literal("paused"), z.literal("awaiting-input"), z.literal("awaiting-decision"), z.literal("planning"), z.literal("pausing"), z.literal("cancelling"), z.literal("completed")]).readonly(),
  'revision': z.number().readonly(),
  'currentRunId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'idempotencyKey': z.string().readonly().optional(),
  'createdAt': z.number().readonly(),
})

export const TYPERT_REMOTE = {
  package: '@deepseek-ai/dsh-task',
  descriptors: [
    {
      id: '@deepseek-ai/dsh-task#tasks/cancelPhaseRun',
      service: 'tasks',
      namespace: 'tasks',
      method: 'cancelPhaseRun',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/cancelPhaseRun:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_cancelPhaseRun_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_cancelPhaseRun_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_cancelPhaseRun_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":683,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/clearPhaseScheduling',
      service: 'tasks',
      namespace: 'tasks',
      method: 'clearPhaseScheduling',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/clearPhaseScheduling:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_clearPhaseScheduling_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_clearPhaseScheduling_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_clearPhaseScheduling_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":790,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/completeTask',
      service: 'tasks',
      namespace: 'tasks',
      method: 'completeTask',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/completeTask:taskId',
            schema: _deepseek_ai_dsh_task_tasks_completeTask_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_completeTask_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRecord',
        schema: _deepseek_ai_dsh_task_tasks_completeTask_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":387,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/confirmCreateTask',
      service: 'tasks',
      namespace: 'tasks',
      method: 'confirmCreateTask',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'recipeId',
          wire: 'recipeId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/confirmCreateTask:recipeId',
            schema: _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_0$schema,
          },
        },
        {
          name: 'goal',
          wire: 'goal',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/confirmCreateTask:goal',
            schema: _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_1$schema,
          },
        },
        {
          name: 'inheritSession',
          wire: 'inheritSession',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/confirmCreateTask:inheritSession',
            schema: _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_2$schema,
          },
        },
        {
          name: 'idempotencyKey',
          wire: 'idempotencyKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/confirmCreateTask:idempotencyKey',
            schema: _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_3$schema,
          },
        },
        {
          name: 'sourceSessionId',
          wire: 'sourceSessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/confirmCreateTask:sourceSessionId',
            schema: _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_4$schema,
          },
        },
        {
          name: 'workspaceId',
          wire: 'workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/confirmCreateTask:workspaceId',
            schema: _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_5$schema,
          },
        },
        {
          name: 'actor',
          wire: 'actor',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/confirmCreateTask:actor',
            schema: _deepseek_ai_dsh_task_tasks_confirmCreateTask_parameter_6$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskCreateConfirmResult',
        schema: _deepseek_ai_dsh_task_tasks_confirmCreateTask_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":239,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/createPhaseRun',
      service: 'tasks',
      namespace: 'tasks',
      method: 'createPhaseRun',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'runId',
          wire: 'runId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/createPhaseRun:runId',
            schema: _deepseek_ai_dsh_task_tasks_createPhaseRun_parameter_0$schema,
          },
        },
        {
          name: 'phaseId',
          wire: 'phaseId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/createPhaseRun:phaseId',
            schema: _deepseek_ai_dsh_task_tasks_createPhaseRun_parameter_1$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_createPhaseRun_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_createPhaseRun_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":467,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/createTask',
      service: 'tasks',
      namespace: 'tasks',
      method: 'createTask',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'recipeId',
          wire: 'recipeId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/createTask:recipeId',
            schema: _deepseek_ai_dsh_task_tasks_createTask_parameter_0$schema,
          },
        },
        {
          name: 'workspaceId',
          wire: 'workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/createTask:workspaceId',
            schema: _deepseek_ai_dsh_task_tasks_createTask_parameter_1$schema,
          },
        },
        {
          name: 'actor',
          wire: 'actor',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/createTask:actor',
            schema: _deepseek_ai_dsh_task_tasks_createTask_parameter_2$schema,
          },
        },
        {
          name: 'idempotencyKey',
          wire: 'idempotencyKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/createTask:idempotencyKey',
            schema: _deepseek_ai_dsh_task_tasks_createTask_parameter_3$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRecord',
        schema: _deepseek_ai_dsh_task_tasks_createTask_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":176,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/createTaskRun',
      service: 'tasks',
      namespace: 'tasks',
      method: 'createTaskRun',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/createTaskRun:taskId',
            schema: _deepseek_ai_dsh_task_tasks_createTaskRun_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_createTaskRun_parameter_1$schema,
          },
        },
        {
          name: 'parentRunId',
          wire: 'parentRunId',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/createTaskRun:parentRunId',
            schema: _deepseek_ai_dsh_task_tasks_createTaskRun_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_createTaskRun_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":431,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/failTask',
      service: 'tasks',
      namespace: 'tasks',
      method: 'failTask',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/failTask:taskId',
            schema: _deepseek_ai_dsh_task_tasks_failTask_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_failTask_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRecord',
        schema: _deepseek_ai_dsh_task_tasks_failTask_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":373,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/freezePhaseScheduling',
      service: 'tasks',
      namespace: 'tasks',
      method: 'freezePhaseScheduling',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/freezePhaseScheduling:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_freezePhaseScheduling_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_freezePhaseScheduling_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_freezePhaseScheduling_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":778,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/getPhaseRun',
      service: 'tasks',
      namespace: 'tasks',
      method: 'getPhaseRun',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/getPhaseRun:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_getPhaseRun_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task#tasks/getPhaseRun:result',
        schema: _deepseek_ai_dsh_task_tasks_getPhaseRun_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":838,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/getSubmission',
      service: 'tasks',
      namespace: 'tasks',
      method: 'getSubmission',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'submissionId',
          wire: 'submissionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/getSubmission:submissionId',
            schema: _deepseek_ai_dsh_task_tasks_getSubmission_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task#tasks/getSubmission:result',
        schema: _deepseek_ai_dsh_task_tasks_getSubmission_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":859,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/getTask',
      service: 'tasks',
      namespace: 'tasks',
      method: 'getTask',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/getTask:taskId',
            schema: _deepseek_ai_dsh_task_tasks_getTask_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task#tasks/getTask:result',
        schema: _deepseek_ai_dsh_task_tasks_getTask_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":819,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/listGateResults',
      service: 'tasks',
      namespace: 'tasks',
      method: 'listGateResults',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'submissionId',
          wire: 'submissionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/listGateResults:submissionId',
            schema: _deepseek_ai_dsh_task_tasks_listGateResults_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task#tasks/listGateResults:result',
        schema: _deepseek_ai_dsh_task_tasks_listGateResults_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":869,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/listPhaseRuns',
      service: 'tasks',
      namespace: 'tasks',
      method: 'listPhaseRuns',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'runId',
          wire: 'runId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/listPhaseRuns:runId',
            schema: _deepseek_ai_dsh_task_tasks_listPhaseRuns_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task#tasks/listPhaseRuns:result',
        schema: _deepseek_ai_dsh_task_tasks_listPhaseRuns_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":848,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/listTasks',
      service: 'tasks',
      namespace: 'tasks',
      method: 'listTasks',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task#tasks/listTasks:result',
        schema: _deepseek_ai_dsh_task_tasks_listTasks_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":828,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/markGateChecksStale',
      service: 'tasks',
      namespace: 'tasks',
      method: 'markGateChecksStale',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'submissionId',
          wire: 'submissionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/markGateChecksStale:submissionId',
            schema: _deepseek_ai_dsh_task_tasks_markGateChecksStale_parameter_0$schema,
          },
        },
        {
          name: 'checkIds',
          wire: 'checkIds',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/markGateChecksStale:checkIds',
            schema: _deepseek_ai_dsh_task_tasks_markGateChecksStale_parameter_1$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_markGateChecksStale_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task#tasks/markGateChecksStale:result',
        schema: _deepseek_ai_dsh_task_tasks_markGateChecksStale_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":804,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/markPhaseAwaitingDecision',
      service: 'tasks',
      namespace: 'tasks',
      method: 'markPhaseAwaitingDecision',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/markPhaseAwaitingDecision:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_markPhaseAwaitingDecision_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_markPhaseAwaitingDecision_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_markPhaseAwaitingDecision_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":736,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/markPhaseAwaitingInput',
      service: 'tasks',
      namespace: 'tasks',
      method: 'markPhaseAwaitingInput',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/markPhaseAwaitingInput:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_markPhaseAwaitingInput_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_markPhaseAwaitingInput_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_markPhaseAwaitingInput_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":724,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/markPhaseFailed',
      service: 'tasks',
      namespace: 'tasks',
      method: 'markPhaseFailed',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/markPhaseFailed:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_markPhaseFailed_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_markPhaseFailed_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_markPhaseFailed_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":672,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/markPhasePassed',
      service: 'tasks',
      namespace: 'tasks',
      method: 'markPhasePassed',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/markPhasePassed:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_markPhasePassed_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_markPhasePassed_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_markPhasePassed_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":661,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/markPhaseStale',
      service: 'tasks',
      namespace: 'tasks',
      method: 'markPhaseStale',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/markPhaseStale:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_markPhaseStale_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_markPhaseStale_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_markPhaseStale_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":697,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/markPhaseSuperseded',
      service: 'tasks',
      namespace: 'tasks',
      method: 'markPhaseSuperseded',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/markPhaseSuperseded:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_markPhaseSuperseded_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_markPhaseSuperseded_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_markPhaseSuperseded_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":712,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/markTaskAwaitingDecision',
      service: 'tasks',
      namespace: 'tasks',
      method: 'markTaskAwaitingDecision',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/markTaskAwaitingDecision:taskId',
            schema: _deepseek_ai_dsh_task_tasks_markTaskAwaitingDecision_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_markTaskAwaitingDecision_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRecord',
        schema: _deepseek_ai_dsh_task_tasks_markTaskAwaitingDecision_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":406,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/recordGateCheck',
      service: 'tasks',
      namespace: 'tasks',
      method: 'recordGateCheck',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'result',
          wire: 'result',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#GateCheckResult',
            schema: _deepseek_ai_dsh_task_tasks_recordGateCheck_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#GateCheckResult',
        schema: _deepseek_ai_dsh_task_tasks_recordGateCheck_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":640,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/recordPhaseSession',
      service: 'tasks',
      namespace: 'tasks',
      method: 'recordPhaseSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/recordPhaseSession:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_recordPhaseSession_parameter_0$schema,
          },
        },
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/recordPhaseSession:sessionId',
            schema: _deepseek_ai_dsh_task_tasks_recordPhaseSession_parameter_1$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_recordPhaseSession_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_recordPhaseSession_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":764,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/recordSubmission',
      service: 'tasks',
      namespace: 'tasks',
      method: 'recordSubmission',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'submission',
          wire: 'submission',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#PhaseSubmission',
            schema: _deepseek_ai_dsh_task_tasks_recordSubmission_parameter_0$schema,
          },
        },
        {
          name: 'environment',
          wire: 'environment',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#SubmissionEnvironmentFacts',
            schema: _deepseek_ai_dsh_task_tasks_recordSubmission_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseSubmission',
        schema: _deepseek_ai_dsh_task_tasks_recordSubmission_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":562,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/requestCancel',
      service: 'tasks',
      namespace: 'tasks',
      method: 'requestCancel',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/requestCancel:taskId',
            schema: _deepseek_ai_dsh_task_tasks_requestCancel_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_requestCancel_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRecord',
        schema: _deepseek_ai_dsh_task_tasks_requestCancel_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":351,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/requestPatch',
      service: 'tasks',
      namespace: 'tasks',
      method: 'requestPatch',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/requestPatch:taskId',
            schema: _deepseek_ai_dsh_task_tasks_requestPatch_parameter_0$schema,
          },
        },
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/requestPatch:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_requestPatch_parameter_1$schema,
          },
        },
        {
          name: 'note',
          wire: 'note',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/requestPatch:note',
            schema: _deepseek_ai_dsh_task_tasks_requestPatch_parameter_2$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_requestPatch_parameter_3$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseSubmission',
        schema: _deepseek_ai_dsh_task_tasks_requestPatch_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":578,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/requestPause',
      service: 'tasks',
      namespace: 'tasks',
      method: 'requestPause',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/requestPause:taskId',
            schema: _deepseek_ai_dsh_task_tasks_requestPause_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_requestPause_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRecord',
        schema: _deepseek_ai_dsh_task_tasks_requestPause_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":318,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/resume',
      service: 'tasks',
      namespace: 'tasks',
      method: 'resume',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/resume:taskId',
            schema: _deepseek_ai_dsh_task_tasks_resume_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_resume_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRecord',
        schema: _deepseek_ai_dsh_task_tasks_resume_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":340,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/resumePhaseFromAwaiting',
      service: 'tasks',
      namespace: 'tasks',
      method: 'resumePhaseFromAwaiting',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/resumePhaseFromAwaiting:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_resumePhaseFromAwaiting_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_resumePhaseFromAwaiting_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_resumePhaseFromAwaiting_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":749,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/resumeTaskFromDecision',
      service: 'tasks',
      namespace: 'tasks',
      method: 'resumeTaskFromDecision',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/resumeTaskFromDecision:taskId',
            schema: _deepseek_ai_dsh_task_tasks_resumeTaskFromDecision_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_resumeTaskFromDecision_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRecord',
        schema: _deepseek_ai_dsh_task_tasks_resumeTaskFromDecision_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":418,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/settleCancel',
      service: 'tasks',
      namespace: 'tasks',
      method: 'settleCancel',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/settleCancel:taskId',
            schema: _deepseek_ai_dsh_task_tasks_settleCancel_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_settleCancel_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRecord',
        schema: _deepseek_ai_dsh_task_tasks_settleCancel_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":362,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/settlePause',
      service: 'tasks',
      namespace: 'tasks',
      method: 'settlePause',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/settlePause:taskId',
            schema: _deepseek_ai_dsh_task_tasks_settlePause_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_settlePause_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRecord',
        schema: _deepseek_ai_dsh_task_tasks_settlePause_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":329,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/startGate',
      service: 'tasks',
      namespace: 'tasks',
      method: 'startGate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'submissionId',
          wire: 'submissionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/startGate:submissionId',
            schema: _deepseek_ai_dsh_task_tasks_startGate_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_startGate_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_startGate_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":629,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/startPhaseRun',
      service: 'tasks',
      namespace: 'tasks',
      method: 'startPhaseRun',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'phaseRunId',
          wire: 'phaseRunId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/startPhaseRun:phaseRunId',
            schema: _deepseek_ai_dsh_task_tasks_startPhaseRun_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_startPhaseRun_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#PhaseRunRecord',
        schema: _deepseek_ai_dsh_task_tasks_startPhaseRun_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":494,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-task#tasks/startTask',
      service: 'tasks',
      namespace: 'tasks',
      method: 'startTask',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'taskId',
          wire: 'taskId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task#tasks/startTask:taskId',
            schema: _deepseek_ai_dsh_task_tasks_startTask_parameter_0$schema,
          },
        },
        {
          name: 'mutation',
          wire: 'mutation',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-task/types#TaskMutationContext',
            schema: _deepseek_ai_dsh_task_tasks_startTask_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-task/types#TaskRecord',
        schema: _deepseek_ai_dsh_task_tasks_startTask_result$schema,
      },
      sourceLocation: {"file":"packages/task-flow/task/src/index.ts","line":307,"column":9},
    },
  ],
}

export default TYPERT_REMOTE
