/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { GateCheckResult, PhaseRunRecord, PhaseSubmission, SubmissionEnvironmentFacts, TaskCreateConfirmResult, TaskMutationContext, TaskRecord, TaskRunRecord } from '../src/task/types.ts'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7461736b73 {
    cancelPhaseRun: (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    clearPhaseScheduling: (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    completeTask: (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    confirmCreateTask: (recipeId: string, goal: string, inheritSession: boolean, idempotencyKey: string, sourceSessionId: string, workspaceId: string, actor: string) => Promise<RemoteResult<TaskCreateConfirmResult>>
    createPhaseRun: (runId: string, phaseId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    createTask: (recipeId: string, workspaceId: string, actor: string, idempotencyKey: string) => Promise<RemoteResult<TaskRecord>>
    createTaskRun: (taskId: string, mutation: TaskMutationContext, parentRunId?: string) => Promise<RemoteResult<TaskRunRecord>>
    failTask: (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    freezePhaseScheduling: (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    getPhaseRun: (phaseRunId: string) => Promise<RemoteResult<PhaseRunRecord | undefined>>
    getSubmission: (submissionId: string) => Promise<RemoteResult<PhaseSubmission | undefined>>
    getTask: (taskId: string) => Promise<RemoteResult<TaskRecord | undefined>>
    listGateResults: (submissionId: string) => Promise<RemoteResult<GateCheckResult[]>>
    listPhaseRuns: (runId: string) => Promise<RemoteResult<PhaseRunRecord[]>>
    listTasks: () => Promise<RemoteResult<TaskRecord[]>>
    markGateChecksStale: (submissionId: string, checkIds: readonly string[], mutation: TaskMutationContext) => Promise<RemoteResult<GateCheckResult[]>>
    markPhaseAwaitingDecision: (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    markPhaseAwaitingInput: (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    markPhaseFailed: (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    markPhasePassed: (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    markPhaseStale: (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    markPhaseSuperseded: (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    markTaskAwaitingDecision: (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    recordGateCheck: (result: GateCheckResult) => Promise<RemoteResult<GateCheckResult>>
    recordPhaseSession: (phaseRunId: string, sessionId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    recordSubmission: (submission: PhaseSubmission, environment: SubmissionEnvironmentFacts) => Promise<RemoteResult<PhaseSubmission>>
    requestCancel: (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    requestPatch: (taskId: string, phaseRunId: string, note: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseSubmission>>
    requestPause: (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    resume: (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    resumePhaseFromAwaiting: (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    resumeTaskFromDecision: (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    settleCancel: (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    settlePause: (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    startGate: (submissionId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    startPhaseRun: (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    startTask: (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
  }
  interface TypertRemoteMap {
    'tasks/cancelPhaseRun': (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/clearPhaseScheduling': (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/completeTask': (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    'tasks/confirmCreateTask': (recipeId: string, goal: string, inheritSession: boolean, idempotencyKey: string, sourceSessionId: string, workspaceId: string, actor: string) => Promise<RemoteResult<TaskCreateConfirmResult>>
    'tasks/createPhaseRun': (runId: string, phaseId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/createTask': (recipeId: string, workspaceId: string, actor: string, idempotencyKey: string) => Promise<RemoteResult<TaskRecord>>
    'tasks/createTaskRun': (taskId: string, mutation: TaskMutationContext, parentRunId?: string) => Promise<RemoteResult<TaskRunRecord>>
    'tasks/failTask': (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    'tasks/freezePhaseScheduling': (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/getPhaseRun': (phaseRunId: string) => Promise<RemoteResult<PhaseRunRecord | undefined>>
    'tasks/getSubmission': (submissionId: string) => Promise<RemoteResult<PhaseSubmission | undefined>>
    'tasks/getTask': (taskId: string) => Promise<RemoteResult<TaskRecord | undefined>>
    'tasks/listGateResults': (submissionId: string) => Promise<RemoteResult<GateCheckResult[]>>
    'tasks/listPhaseRuns': (runId: string) => Promise<RemoteResult<PhaseRunRecord[]>>
    'tasks/listTasks': () => Promise<RemoteResult<TaskRecord[]>>
    'tasks/markGateChecksStale': (submissionId: string, checkIds: readonly string[], mutation: TaskMutationContext) => Promise<RemoteResult<GateCheckResult[]>>
    'tasks/markPhaseAwaitingDecision': (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/markPhaseAwaitingInput': (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/markPhaseFailed': (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/markPhasePassed': (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/markPhaseStale': (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/markPhaseSuperseded': (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/markTaskAwaitingDecision': (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    'tasks/recordGateCheck': (result: GateCheckResult) => Promise<RemoteResult<GateCheckResult>>
    'tasks/recordPhaseSession': (phaseRunId: string, sessionId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/recordSubmission': (submission: PhaseSubmission, environment: SubmissionEnvironmentFacts) => Promise<RemoteResult<PhaseSubmission>>
    'tasks/requestCancel': (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    'tasks/requestPatch': (taskId: string, phaseRunId: string, note: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseSubmission>>
    'tasks/requestPause': (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    'tasks/resume': (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    'tasks/resumePhaseFromAwaiting': (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/resumeTaskFromDecision': (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    'tasks/settleCancel': (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    'tasks/settlePause': (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
    'tasks/startGate': (submissionId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/startPhaseRun': (phaseRunId: string, mutation: TaskMutationContext) => Promise<RemoteResult<PhaseRunRecord>>
    'tasks/startTask': (taskId: string, mutation: TaskMutationContext) => Promise<RemoteResult<TaskRecord>>
  }
  interface TypertRemoteNamespaceMap {
    'tasks': TypertRemoteNamespace$7461736b73
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
